# Generated by Django 3.0.7 on 2020-06-09 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contents', models.TextField(blank=True)),
                ('state', models.CharField(max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('min_bid', models.IntegerField()),
                ('max_bid', models.IntegerField()),
                ('winning_bid', models.IntegerField()),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.IntegerField()),
                ('is_valid', models.BooleanField()),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auction.Auction')),
            ],
        ),
    ]
