# Generated by Django 3.0.7 on 2020-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winning_bid',
            field=models.IntegerField(null=True),
        ),
    ]
