# Generated by Django 3.0.7 on 2020-06-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='auctionhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
