# Generated by Django 3.0.7 on 2020-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200611_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='now_bid',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
