# Generated by Django 3.0.7 on 2020-06-11 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20200611_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winning_user_id',
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_auction_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
